# Generated by Django 2.0.6 on 2018-06-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CID', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('TIME', models.CharField(blank=True, max_length=100)),
                ('CONTENT', models.CharField(blank=True, max_length=350)),
                ('WRITER', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Follows',
            fields=[
                ('FID', models.AutoField(primary_key=True, serialize=False)),
                ('PID', models.IntegerField()),
                ('TIME', models.CharField(blank=True, max_length=100)),
                ('CONTENT', models.CharField(blank=True, max_length=550)),
                ('WRITER', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PID', models.IntegerField()),
                ('HOT', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('PID', models.AutoField(primary_key=True, serialize=False)),
                ('TITLE', models.CharField(max_length=100)),
                ('CONTENT', models.CharField(blank=True, max_length=550)),
                ('TIME', models.CharField(blank=True, max_length=100)),
                ('WRITER', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('PID', models.IntegerField(primary_key=True, serialize=False)),
                ('NAME', models.CharField(max_length=100)),
                ('DATE', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
